name: auth_standalone

services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres_auth
      - redis
    env_file:
      - auth_service/.env.auth
    volumes:
      - ./auth_service/keys:/app/keys:ro

  postgres_auth:
    image: postgres:16
    restart: always
    env_file:
      - auth_service/.env.auth
    ports:
      - "15433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_auth_data:
  redis_data:
